name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        type: choice
        required: true
        options:
          - devl
          - prod
          - test
        default: devl
      branch:
        description: Branch to deploy
        type: string
        required: true
        options: ${{ github.branches}}
        default: main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploying"